version: '3.7'
services:
  postgres:
    container_name: auth-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: auth-redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - backend

  pgadmin:
    container_name: auth-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - backend

  redisinsight:
    container_name: auth-redisinsight
    image: redis/redisinsight:latest
    restart: always
    ports:
      - '5540:5540'
    depends_on:
      - redis
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
